function StaphPseudomonasinteractiondata = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  STAPHPSEUDOMONASINTERACTIONDATA = IMPORTFILE(FILE) reads data from
%  the first worksheet in the Microsoft Excel spreadsheet file named
%  FILE.  Returns the data as a table.
%
%  STAPHPSEUDOMONASINTERACTIONDATA = IMPORTFILE(FILE, SHEET) reads from
%  the specified worksheet.
%
%  STAPHPSEUDOMONASINTERACTIONDATA = IMPORTFILE(FILE, SHEET, DATALINES)
%  reads from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  StaphPseudomonasinteractiondata = importfile("C:\Users\Tynan\Desktop\Maths\Year 4\Dissertation\Parameter Fitting\Data\221108-Staph-Pseudomonas interaction data.xlsx", "S. aureus mono-culture", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Nov-2022 22:37:13

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["VarName1", "Replica1", "Replica2", "Replica3", "Replica4", "Replica5", "Replica6"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Import the data
StaphPseudomonasinteractiondata = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    StaphPseudomonasinteractiondata = [StaphPseudomonasinteractiondata; tb]; %#ok<AGROW>
end

end